# Generated by vmake version 2020.4

# Define path to each library
LIB_WORK = SPI_sysc
LIB_IEEE = C:/modeltech64_2020.4/win64/../ieee
LIB_STD = C:/modeltech64_2020.4/win64/../std
LIB_SPI_SYSC = SPI_sysc

# Define path to each design unit
IEEE__std_logic_1164 = $(LIB_IEEE)/_lib.qdb
STD__textio = $(LIB_STD)/_lib.qdb
SPI_SYSC__spi_sclk_generator__rtl = $(LIB_SPI_SYSC)/_lib.qdb
SPI_SYSC__spi_sclk_generator = $(LIB_SPI_SYSC)/_lib.qdb
SPI_SYSC__spi_data_write__rtl = $(LIB_SPI_SYSC)/_lib.qdb
SPI_SYSC__spi_data_write = $(LIB_SPI_SYSC)/_lib.qdb
SPI_SYSC__spi_cs_generator__rtl = $(LIB_SPI_SYSC)/_lib.qdb
SPI_SYSC__spi_cs_generator = $(LIB_SPI_SYSC)/_lib.qdb
SPI_SYSC__bidir_pin__struct = $(LIB_SPI_SYSC)/_lib.qdb
SPI_SYSC__bidir_pin = $(LIB_SPI_SYSC)/_lib.qdb
SPI_SYSC__bidir__maxpld = $(LIB_SPI_SYSC)/_lib.qdb
SPI_SYSC__bidir = $(LIB_SPI_SYSC)/_lib.qdb
VCOM = vcom
VLOG = vlog
VOPT = vopt
SCCOM = sccom

whole_library : \
$(LIB_SPI_SYSC)/_lib.qdb

$(LIB_SPI_SYSC)/_lib.qdb : SPI_sysc/tristate_pin.vhdl \
		$(STD__textio) \
		$(IEEE__std_logic_1164) SPI_sysc/spi_cs_gen.vhdl \
		$(STD__textio) \
		$(IEEE__std_logic_1164) SPI_sysc/spi_data_write.vhdl \
		$(STD__textio) \
		$(IEEE__std_logic_1164) SPI_sysc/spi_sclk_gen.vhdl \
		$(STD__textio) \
		$(IEEE__std_logic_1164)
	$(VCOM) -2002 -work SPI_sysc  SPI_sysc/tristate_pin.vhdl
	$(VCOM) -2002 -work SPI_sysc  SPI_sysc/spi_cs_gen.vhdl
	$(VCOM) -2002 -work SPI_sysc  SPI_sysc/spi_data_write.vhdl
	$(VCOM) -2002 -work SPI_sysc  SPI_sysc/spi_sclk_gen.vhdl

