-- ----------------------------------------------------------------------
--  HLS HDL:        VHDL Netlister
--  HLS Version:    2021.1_1/966904 Production Release
--  HLS Date:       Thu Nov 11 21:13:39 PST 2021
-- 
--  Generated by:   jese@ubuntu
--  Generated date: Mon Apr 11 02:28:37 2022
-- ----------------------------------------------------------------------

-- 
-- ------------------------------------------------------------------
--  Design Unit:    spi_adxl_top_generate_sclk
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;


ENTITY spi_adxl_top_generate_sclk IS
  PORT(
    CLK : IN STD_LOGIC;
    MOSI : OUT STD_LOGIC;
    MISO : IN STD_LOGIC
  );
END spi_adxl_top_generate_sclk;

ARCHITECTURE v19 OF spi_adxl_top_generate_sclk IS
  -- Default Constants

BEGIN
  PROCESS (CLK)
  BEGIN
    IF CLK'EVENT AND ( CLK = '1' ) THEN
      MOSI <= MISO;
    END IF;
  END PROCESS;
END v19;

-- ------------------------------------------------------------------
--  Design Unit:    spi_adxl_top
-- ------------------------------------------------------------------

LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;


ENTITY spi_adxl_top IS
  PORT(
    CLK : IN STD_LOGIC;
    SCLK : OUT STD_LOGIC;
    MOSI : OUT STD_LOGIC;
    MISO : IN STD_LOGIC;
    DATA_IN : IN STD_LOGIC_VECTOR (7 DOWNTO 0)
  );
END spi_adxl_top;

ARCHITECTURE v19 OF spi_adxl_top IS
  -- Default Constants

  COMPONENT spi_adxl_top_generate_sclk
    PORT(
      CLK : IN STD_LOGIC;
      MOSI : OUT STD_LOGIC;
      MISO : IN STD_LOGIC
    );
  END COMPONENT;
BEGIN
  spi_adxl_top_generate_sclk_inst : spi_adxl_top_generate_sclk
    PORT MAP(
      CLK => CLK,
      MOSI => MOSI,
      MISO => MISO
    );
END v19;



